[versions]

bignum = "0.3.10"
compose = "1.9.3"
composeHotReload = "1.0.0"
koalaplot = "0.9.1"
kotlin-plugin = "2.2.0"
kotlin-wrappers = "1.0.0-pre.668"
kotlinx-datetime = "0.7.1-0.6.x-compat"

[libraries]

bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
koalaplot = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot" }

kotlin-wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlin-wrappers" }
kotlin-wrappers-emotion = { module = "org.jetbrains.kotlin-wrappers:kotlin-emotion" } # typed CSS styles
kotlin-wrappers-mui-base = { module = "org.jetbrains.kotlin-wrappers:kotlin-mui-base" }
kotlin-wrappers-mui-icons-material = { module = "org.jetbrains.kotlin-wrappers:kotlin-mui-icons-material" }
kotlin-wrappers-react-core = { module = "org.jetbrains.kotlin-wrappers:kotlin-react" }
kotlin-wrappers-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
